version: '3'

services:
  back:
    build: 
      context: ./back/
      dockerfile: Dockerfile
    tty: true
    image: pbl2-back
    container_name: pbl2-back
    volumes:
      - ./back/src:/app/src
    working_dir: /app/src
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    container_name: db-container
    environment:
      POSTGRES_USER: jbkfxlthkrasiq
      POSTGRES_HOST: ec2-3-218-112-22.compute-1.amazonaws.com
      POSTGRES_PASSWORD: 141aaed2ed68e510aa278a4741e5d96b392190965a76cb98c85abab8dc5fefcf
      POSTGRESS_DB: d63cdmlbgnj93n
    ports:
      - "5432:5432"
    
