version: '3'

services:
  back:
    build: 
      context: ./back/
      dockerfile: Dockerfile
    tty: true
    image: pbl2-back
    container_name: pbl2-back
    volumes:
      - ./back/src:/app/src
    working_dir: /app
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: postgres:11-alpine
    container_name: dbforpbl
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESS_DB: ${POSTGRESS_DB}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"

  front:
    build: front
    working_dir: /app
    tty: false
    volumes: 
      - ./front:/app/front
    ports: 
      - "8080:8080"
