version: '3'

services:
  back:
    build: 
      context: ./back/
      dockerfile: Dockerfile
    tty: true
    image: pbl2-back
    container_name: pbl2-back
    volumes:
      - ./back/src:/app/src
    working_dir: /app/src
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:11-alpine
    container_name: db-container4pbl
    environment:
      PGUSER: ${POSTGRES_USER}
      PGHOST: ${POSTGRES_HOST}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRESS_DB}
      PGPORT: 5432
    ports:
      - "5432:5432"

  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    volumes: 
      - ./front:/app/front
    ports: 
      - "8080:8080"
