version: '3'

services:
  back:
    build: back
    working_dir: /app/src
    tty: true
    volumes:
      - ./back/src:/app/src
    ports:
      - "8080:3000"
  front:
    build: front
    working_dir: /app
    tty: true
    volumes: 
      - ./front:/app/front
    ports: 
      - "3000:3000"